FROM node:14.15
WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .
COPY ./lerna.json .

RUN yarn install
RUN npm i -g lerna
RUN lerna bootstrap

RUN lerna run build

EXPOSE 3001
CMD ["lerna", "run", "start"]
