version: '3.8'
services:
    app:
        build:
            dockerfile: ./Dockerfile
            context: .
        ports:
            - 3000:3000
        volumes:
            - '.:/app'
            - '/app/node_modules'
        # https://github.com/facebook/create-react-app/issues/8688
        stdin_open: true
        command: 'serve -l 3000 packages/admin-app/build'

    storybook:
        build:
            dockerfile: ./Dockerfile
            context: .
        ports:
            - 6006:6006
        volumes:
            - '.:/app'
            - '/app/node_modules'
        command: 'serve -l 6006 packages/library/storybook-static'
