name: Npm Deploy

on:
    push:
        branches:
            - feature/api-client
    milestone:
        types: [closed]
    repository_dispatch:
        types: [milestone_closed]

jobs:
    build:
        name: Build and Deploy npm
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: make install
            - name: Lint
              run: make lint
            - name: Build
              run: make build
            - name: Update version
              run: npm version patch
            - name: Publish npm Package
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_DEPLOY_TOKEN}}
