name: Npm Deploy

on:
    push:
        branches:
            - main
    milestone:
        types: [closed]
    repository_dispatch:
        types: [milestone_closed]

jobs:
    build:
        name: Code Analysis
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: make install
            - name: Lint
              run: make lint
            - name: Build
              run: make build
            - name: Test
              run: make test
